#cloud-config
network:
  version: 2
  ethernets: 
    enp1s0:
      dhcp4: no
      addresses: [192.168.122.11/24]
      nameservers: 
        addresses: [192.168.122.1]
      routes:
      - to: 0.0.0.0/0
        via: 192.168.122.1


