---
# tasks file for setup
- name: Allow release-info to change for APT repositories
  become: yes
  command: apt-get update -y --allow-releaseinfo-change
 
- name: Upgrade all apt packages
  become: yes
  apt:
    upgrade: dist
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  register: task_result
  until: task_result is success
  retries: 20
  delay: 2
 
- name: Show current kernel
  command: uname -r
  register: kernel_version
 
- debug: msg="{{ kernel_version.stdout }}"
 
- name: Check if a reboot is needed for Debian and Ubuntu boxes
  become: yes
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no
 
- name: Reboot the Debian or Ubuntu server
  become: yes
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists
 
- name: Install additional packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  register: task_result
  until: task_result is success
  retries: 20
  delay: 2
  vars:
    packages:
      - arp-scan 

- name: Show current kernel
  command: uname -r
  register: kernel_version2
 
- debug: msg="{{ kernel_version2.stdout }}"
...
