---
# tasks file for helm-mypythonapp
- name: Update repo cache to show additions
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: Deploy My-Python-App 
  kubernetes.core.helm:
    name: mypythonapp 
    chart_ref: custom-repo/mypythonapp
    release_namespace: test2
    create_namespace: false
    chart_version: 0.0.2
    values:
      service:
        type: ClusterIP
      restartPolicy: Never
  register: cmd_out

- debug:
    msg: "{{ cmd_out.stdout }}"
...
